
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author Rahul
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    } 
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle4 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle5 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle6 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle12 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle13 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle8 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle14 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle7 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle9 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        setForeground(new java.awt.Color(102, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/Webp.net-resizeimage (1).jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 750, 470));

        rSMaterialButtonCircle1.setText("aDD STAFFS");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 240, 90));

        rSMaterialButtonCircle2.setText("BOOK DETAILS");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 240, 90));

        rSMaterialButtonCircle3.setText("Add BOOKS");
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 240, 90));

        rSMaterialButtonCircle4.setText("ISSUE BOOKS");
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 240, 90));

        rSMaterialButtonCircle5.setText("statics");
        rSMaterialButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle5ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, 240, 90));

        rSMaterialButtonCircle6.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle6.setText("logout");
        rSMaterialButtonCircle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle6ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 10, 90, 50));

        rSMaterialButtonCircle12.setText("STAFF DETAILS");
        rSMaterialButtonCircle12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle12ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 240, 240, 90));

        rSMaterialButtonCircle13.setText("New Student");
        rSMaterialButtonCircle13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle13ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 90));

        rSMaterialButtonCircle8.setText("return books");
        rSMaterialButtonCircle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle8ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 680, 240, 90));

        rSMaterialButtonCircle14.setText("student details");
        rSMaterialButtonCircle14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle14ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 240, 90));

        rSMaterialButtonCircle7.setText("change password");
        rSMaterialButtonCircle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle7ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 500, 250, 100));

        rSMaterialButtonCircle9.setText("Check Biodata of Student");
        rSMaterialButtonCircle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle9ActionPerformed(evt);
            }
        });
        getContentPane().add(rSMaterialButtonCircle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 270, 90));

        setSize(new java.awt.Dimension(1533, 840));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle5ActionPerformed
        // TODO add your handling code here:
        Statics r=new Statics();
        r.setVisible(true);
        
        
    }//GEN-LAST:event_rSMaterialButtonCircle5ActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        // TODO add your handling code here:
        Issuebook r=new Issuebook();
        r.setVisible(true);
        
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
            AddStaff r=new AddStaff();
        r.setVisible(true);
        
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void rSMaterialButtonCircle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6ActionPerformed
        // TODO add your handling code here:
        LoginPage r=new LoginPage();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle6ActionPerformed

    private void rSMaterialButtonCircle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle8ActionPerformed
        // TODO add your handling code here:
         Returnbooks r=new Returnbooks();
        r.setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonCircle8ActionPerformed

    private void rSMaterialButtonCircle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle7ActionPerformed
        // TODO add your handling code here:
      new ChangePassword().setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonCircle7ActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
      Bookdetails r=new Bookdetails();
        r.setVisible(true);
        
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed
          
    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        Addbooks r=new Addbooks();
        r.setVisible(true);
        
        
      
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle9ActionPerformed
        // TODO add your handling code here:
          ShowStudentActivity r=new ShowStudentActivity();
        r.setVisible(true);

    }//GEN-LAST:event_rSMaterialButtonCircle9ActionPerformed

    private void rSMaterialButtonCircle10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle10ActionPerformed
        // TODO add your handling code here:
        StudentDetails r=new StudentDetails();
        r.setVisible(true);
        
    }//GEN-LAST:event_rSMaterialButtonCircle10ActionPerformed

    private void rSMaterialButtonCircle12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle12ActionPerformed
        // TODO add your handling code here:
        Staffdetails r=new Staffdetails();
        r.setVisible(true);
        

    }//GEN-LAST:event_rSMaterialButtonCircle12ActionPerformed

    private void rSMaterialButtonCircle14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle14ActionPerformed
        // TODO add your handling code here:
        StudentDetails r=new StudentDetails();
        r.setVisible(true);
        

    }//GEN-LAST:event_rSMaterialButtonCircle14ActionPerformed

    private void rSMaterialButtonCircle13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle13ActionPerformed
        // TODO add your handling code here:
         Newstudent r=new Newstudent();
        r.setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonCircle13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle12;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle13;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle14;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle5;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle6;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle7;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle8;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle9;
    // End of variables declaration//GEN-END:variables
}
